### PR TITLE
Landing page base code and updated bootstrap.sh

### PR DESCRIPTION
**Pull request by thedarianwong**
Is the bootstrap better? 
Landing page is still on progress

### CODE REVIEW

**Comment by hungnguyen3** [comment]
> Is the bootstrap better? Landing page is still on progress

damn you fixed it

**Review by sbshaun — DISMISSED** [review]
LGTM!

**Comment by hungnguyen3** [comment]
> LGTM!

wait a bit, I'll make a change

**Comment by hungnguyen3** [comment]
@sbshaun the README doesn't display the image, it is private image

**Comment by sbshaun** [comment]
> @sbshaun the README doesn't display the image, it is private image

No? can you try to see in this link in Incognito mode? https://github.com/jobless-devs/Jobhub/tree/client-dev

**Comment by hungnguyen3** [comment]
> > @sbshaun the README doesn't display the image, it is private image
> 
> No? can you try to see in this link in Incognito mode? https://github.com/jobless-devs/Jobhub/tree/client-dev

can you compress the image, it's too large my laptop doesn't display literally

**Comment by sbshaun** [comment]
> > > @sbshaun the README doesn't display the image, it is private image
> > 
> > 
> > No? can you try to see in this link in Incognito mode? https://github.com/jobless-devs/Jobhub/tree/client-dev
> 
> can you compress the image, it's too large my laptop doesn't display literally

it makes no sense 😂 it's 2MB, can you try the link on your phone? Even my phone works fine

**Comment by hungnguyen3** [comment]
> > > > @sbshaun the README doesn't display the image, it is private image
> > > 
> > > 
> > > No? can you try to see in this link in Incognito mode? https://github.com/jobless-devs/Jobhub/tree/client-dev
> > 
> > 
> > can you compress the image, it's too large my laptop doesn't display literally
> 
> it makes no sense 😂 it's 2MB, can you try the link on your phone? Even my phone works fine

it doesn't work on my laptop but works on my phone, that's why I asked. But we can just ignore that for now

can you review my new commit? thankss

**Review by sbshaun — APPROVED** [review]

**Pull request merged**
